/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package heladeria;

import java.awt.Color;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sofi
 */
public class shop3 extends javax.swing.JFrame {

    /**
     * Creates new form shop3
     */
    public shop3() {
        initComponents();

        TablaCant_Precios.setForeground(Color.BLACK);
        TablaCant_Precios.setBackground(Color.WHITE);

        //setResizable(false);    // no permite que el tamaño de la ventana se pueda redimensionar.

    }

    int sum = 0;
    int cantidad;
    int precio;
    int total;

    DefaultTableModel model = new DefaultTableModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        butterscotch_budino = new javax.swing.JLabel();
        amarena_cherry = new javax.swing.JLabel();
        passion_fruit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mixed_berry = new javax.swing.JLabel();
        italian_custard = new javax.swing.JLabel();
        chocolate_fondente = new javax.swing.JLabel();
        roasted_banana = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaCant_Precios = new javax.swing.JTable();
        TOTAL = new javax.swing.JLabel();
        muestraTotal = new javax.swing.JTextField();
        butterscotch_budinoBOTON = new javax.swing.JCheckBox();
        budinoSpinner = new javax.swing.JSpinner();
        amarena_cherryBOTON = new javax.swing.JCheckBox();
        amarenaSpinner = new javax.swing.JSpinner();
        passion_fruitBOTON = new javax.swing.JCheckBox();
        chocofondSpinner = new javax.swing.JSpinner();
        passionfruitSpinner = new javax.swing.JSpinner();
        rum_raisinBOTON = new javax.swing.JCheckBox();
        rumSpinner = new javax.swing.JSpinner();
        mixed_berryBOTON = new javax.swing.JCheckBox();
        mixedberrySpinner = new javax.swing.JSpinner();
        italian_custardBOTON = new javax.swing.JCheckBox();
        italianSpinner = new javax.swing.JSpinner();
        chocolate_fondenteBOTON = new javax.swing.JCheckBox();
        roasted_bananaBOTON = new javax.swing.JCheckBox();
        bananaSpinner = new javax.swing.JSpinner();
        bourbon_vanillaBOTON = new javax.swing.JCheckBox();
        vanillaSpinner = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        titulo.setFont(new java.awt.Font("Serif", 2, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("ICE CREAM SHOP");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(titulo)
                                .addGap(336, 336, 336))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(27, Short.MAX_VALUE)
                                .addComponent(titulo)
                                .addGap(20, 20, 20))
        );

        jPanel2.setBackground(new java.awt.Color(242, 183, 183));

        butterscotch_budino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes3/DULCEDELECHE.png"))); // NOI18N

        amarena_cherry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes3/COOKIES.png"))); // NOI18N

        passion_fruit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes3/MANGO.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes3/CHOCOBLANCO.png"))); // NOI18N

        mixed_berry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes3/FRUTILLA.png"))); // NOI18N

        italian_custard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes3/DULCEGRANIZADO.png"))); // NOI18N

        chocolate_fondente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes3/CHOCOLATE.png"))); // NOI18N

        roasted_banana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes3/BANANA.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes3/VAINILLA.png"))); // NOI18N

        TablaCant_Precios.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "Item", "Precio", "Cantidad", "TOTAL"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaCant_Precios);

        TOTAL.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        TOTAL.setText("TOTAL");

        muestraTotal.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        muestraTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        butterscotch_budinoBOTON.setText("Butterscotch Budino");

        amarena_cherryBOTON.setText("Amarena Cherry");

        passion_fruitBOTON.setText("Passion Fruit");

        passionfruitSpinner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        rum_raisinBOTON.setText("Rum Raisin");

        mixed_berryBOTON.setText("Mixed Berry");

        italian_custardBOTON.setText("Italian Custard");

        chocolate_fondenteBOTON.setText("Chocolate Fondente");

        roasted_bananaBOTON.setText("Roasted Banana");

        bourbon_vanillaBOTON.setText("Bourbon Vanilla");

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(butterscotch_budino)
                                                                .addGap(46, 46, 46)
                                                                .addComponent(amarena_cherry))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                                                .addComponent(jLabel2)
                                                                                .addGap(53, 53, 53))
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                                                .addComponent(chocolate_fondente)
                                                                                .addGap(50, 50, 50)))
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(roasted_banana)
                                                                        .addComponent(mixed_berry)
                                                                        .addComponent(amarena_cherryBOTON)
                                                                        .addComponent(mixed_berryBOTON)
                                                                        .addComponent(roasted_bananaBOTON)
                                                                        .addComponent(amarenaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(mixedberrySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(bananaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(54, 54, 54)
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(passion_fruitBOTON)
                                                                        .addComponent(passion_fruit)
                                                                        .addComponent(passionfruitSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(47, 47, 47)
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(italian_custardBOTON)
                                                                        .addComponent(italian_custard)
                                                                        .addComponent(italianSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(bourbon_vanillaBOTON)
                                                                        .addComponent(jLabel3)
                                                                        .addComponent(vanillaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addComponent(butterscotch_budinoBOTON)
                                        .addComponent(rum_raisinBOTON, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(chocolate_fondenteBOTON)
                                        .addComponent(budinoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(rumSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(chocofondSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(TOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(muestraTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jScrollPane1)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(muestraTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TOTAL))
                                .addGap(17, 17, 17))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(amarena_cherry)
                                        .addComponent(butterscotch_budino)
                                        .addComponent(passion_fruit))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(butterscotch_budinoBOTON)
                                        .addComponent(amarena_cherryBOTON)
                                        .addComponent(passion_fruitBOTON))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(budinoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(amarenaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(passionfruitSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(italian_custard, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(mixed_berry, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(rum_raisinBOTON)
                                                        .addComponent(mixed_berryBOTON)
                                                        .addComponent(italian_custardBOTON))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(rumSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(mixedberrySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(italianSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(14, 14, 14)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(chocolate_fondente)
                                                        .addComponent(roasted_banana)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(111, 111, 111)
                                                .addComponent(jLabel3)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(chocolate_fondenteBOTON)
                                        .addComponent(roasted_bananaBOTON)
                                        .addComponent(bourbon_vanillaBOTON))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(chocofondSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bananaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(vanillaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // ACCION DEL BOTON ADD
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        if(butterscotch_budinoBOTON.isSelected()){
            cantidad = Integer.parseInt(budinoSpinner.getValue().toString());

            model = (DefaultTableModel)TablaCant_Precios.getModel();

            model.addRow(new Object[]
                    {
                            butterscotch_budinoBOTON.getText(),
                            precio = 150,
                            cantidad,
                            total = cantidad * precio,
                    });
        }
        if(amarena_cherryBOTON.isSelected()){
            cantidad = Integer.parseInt(amarenaSpinner.getValue().toString());

            model = (DefaultTableModel)TablaCant_Precios.getModel();

            model.addRow(new Object[]
                    {
                            amarena_cherryBOTON.getText(),
                            precio = 120,
                            cantidad,
                            total = cantidad * precio,
                    });
        }
        if(passion_fruitBOTON.isSelected()){
            cantidad = Integer.parseInt(passionfruitSpinner.getValue().toString());

            model = (DefaultTableModel)TablaCant_Precios.getModel();

            model.addRow(new Object[]
                    {
                            passion_fruitBOTON.getText(),
                            precio = 110,
                            cantidad,
                            total = cantidad * precio,
                    });
        } if(rum_raisinBOTON.isSelected()){
            cantidad = Integer.parseInt(rumSpinner.getValue().toString());

            model = (DefaultTableModel)TablaCant_Precios.getModel();

            model.addRow(new Object[]
                    {
                            rum_raisinBOTON.getText(),
                            precio = 140,
                            cantidad,
                            total = cantidad * precio,
                    });
        } if(mixed_berryBOTON.isSelected()){
            cantidad = Integer.parseInt(mixedberrySpinner.getValue().toString());

            model = (DefaultTableModel)TablaCant_Precios.getModel();

            model.addRow(new Object[]
                    {
                            mixed_berryBOTON.getText(),
                            precio = 130,
                            cantidad,
                            total = cantidad * precio,
                    });
        } if(italian_custardBOTON.isSelected()){
            cantidad = Integer.parseInt(italianSpinner.getValue().toString());

            model = (DefaultTableModel)TablaCant_Precios.getModel();

            model.addRow(new Object[]
                    {
                            italian_custardBOTON.getText(),
                            precio = 160,
                            cantidad,
                            total = cantidad * precio,
                    });
        } if(chocolate_fondenteBOTON.isSelected()){
            cantidad = Integer.parseInt(chocofondSpinner.getValue().toString());

            model = (DefaultTableModel)TablaCant_Precios.getModel();

            model.addRow(new Object[]
                    {
                            chocolate_fondenteBOTON.getText(),
                            precio = 140,
                            cantidad,
                            total = cantidad * precio,
                    });
        } if(roasted_bananaBOTON.isSelected()){
            cantidad = Integer.parseInt(bananaSpinner.getValue().toString());

            model = (DefaultTableModel)TablaCant_Precios.getModel();

            model.addRow(new Object[]
                    {
                            roasted_bananaBOTON.getText(),
                            precio = 180,
                            cantidad,
                            total = cantidad * precio,
                    });
        } if(bourbon_vanillaBOTON.isSelected()){
            cantidad = Integer.parseInt(vanillaSpinner.getValue().toString());

            model = (DefaultTableModel)TablaCant_Precios.getModel();

            model.addRow(new Object[]
                    {
                            bourbon_vanillaBOTON.getText(),
                            precio = 110,
                            cantidad,
                            total = cantidad * precio,
                    });
        }

        for(int i=0; i < TablaCant_Precios.getRowCount(); i++){
            sum = sum + Integer.parseInt(TablaCant_Precios.getValueAt(i, 3).toString());    // calcula la ultima columna de la tabla
        }

        muestraTotal.setText(Integer.toString(sum));

    }//GEN-LAST:event_jButton1ActionPerformed

    /*
    private void orden() {
        final String orden = "Tu orden de HELADO - Tiene un Total de: $" + muestraTotal + "\n"
                + "Confirmas la Orden?" + "\n";

        JOptionPane.showConfirmDialog(null, orden);

    }

     */

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(shop3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(shop3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(shop3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(shop3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new shop3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TOTAL;
    private javax.swing.JTable TablaCant_Precios;
    private javax.swing.JSpinner amarenaSpinner;
    private javax.swing.JLabel amarena_cherry;
    private javax.swing.JCheckBox amarena_cherryBOTON;
    private javax.swing.JSpinner bananaSpinner;
    private javax.swing.JCheckBox bourbon_vanillaBOTON;
    private javax.swing.JSpinner budinoSpinner;
    private javax.swing.JLabel butterscotch_budino;
    private javax.swing.JCheckBox butterscotch_budinoBOTON;
    private javax.swing.JSpinner chocofondSpinner;
    private javax.swing.JLabel chocolate_fondente;
    private javax.swing.JCheckBox chocolate_fondenteBOTON;
    private javax.swing.JSpinner italianSpinner;
    private javax.swing.JLabel italian_custard;
    private javax.swing.JCheckBox italian_custardBOTON;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mixed_berry;
    private javax.swing.JCheckBox mixed_berryBOTON;
    private javax.swing.JSpinner mixedberrySpinner;
    private javax.swing.JTextField muestraTotal;
    private javax.swing.JLabel passion_fruit;
    private javax.swing.JCheckBox passion_fruitBOTON;
    private javax.swing.JSpinner passionfruitSpinner;
    private javax.swing.JLabel roasted_banana;
    private javax.swing.JCheckBox roasted_bananaBOTON;
    private javax.swing.JSpinner rumSpinner;
    private javax.swing.JCheckBox rum_raisinBOTON;
    private javax.swing.JLabel titulo;
    private javax.swing.JSpinner vanillaSpinner;
    // End of variables declaration//GEN-END:variables
}
