package TiendaHelados;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author sofi
 */
public class shop extends javax.swing.JFrame implements MouseListener{

    /**
     * Creates new form shop
     */
    public shop() {
        initComponents();

        // sabores
        rum_raisin.addMouseListener(this);
        amarena_cherry.addMouseListener(this);
        passion_fruit.addMouseListener(this);
        butterscotch_budino.addMouseListener(this);
        mixed_berry.addMouseListener(this);
        italian_custard.addMouseListener(this);
        chocolate_fondente.addMouseListener(this);
        roasted_banana.addMouseListener(this);
        bourbon_vanillabean.addMouseListener(this);

        setResizable(false);    // no permite que el tamaño de la ventana se pueda redimensionar.

    }

    DefaultTableModel modelo = new DefaultTableModel();

    /*  -- GRAFICOS -- */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        passion_fruit = new javax.swing.JLabel();
        amarena_cherry = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtsub = new javax.swing.JTextField();
        rum_raisin = new javax.swing.JLabel();
        butterscotch_budino = new javax.swing.JLabel();
        mixed_berry = new javax.swing.JLabel();
        chocolate_fondente = new javax.swing.JLabel();
        italian_custard = new javax.swing.JLabel();
        roasted_banana = new javax.swing.JLabel();
        bourbon_vanillabean = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(242, 183, 183));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "Item", "Precio", "Cantidad", "TOTAL"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTable1);

        passion_fruit.setIcon(new javax.swing.ImageIcon("F:\\Sofia\\MANGO.png")); // NOI18N

        amarena_cherry.setIcon(new javax.swing.ImageIcon("F:\\Sofia\\COOKIES.png")); // NOI18N

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel5.setText("TOTAL");

        txtsub.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        txtsub.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        rum_raisin.setIcon(new javax.swing.ImageIcon("F:\\Sofia\\CHOCOBLANCO.png")); // NOI18N
        rum_raisin.setMaximumSize(new java.awt.Dimension(307, 645));

        butterscotch_budino.setIcon(new javax.swing.ImageIcon("F:\\Sofia\\DULCEDELECHE.png")); // NOI18N
        butterscotch_budino.setMaximumSize(new java.awt.Dimension(307, 645));

        mixed_berry.setIcon(new javax.swing.ImageIcon("F:\\Sofia\\FRUTILLA.png")); // NOI18N
        mixed_berry.setMaximumSize(new java.awt.Dimension(307, 645));

        chocolate_fondente.setIcon(new javax.swing.ImageIcon("F:\\Sofia\\CHOCOLATE.png")); // NOI18N
        chocolate_fondente.setMaximumSize(new java.awt.Dimension(307, 645));

        italian_custard.setIcon(new javax.swing.ImageIcon("F:\\Sofia\\DULCEGRANIZADO.png")); // NOI18N
        italian_custard.setMaximumSize(new java.awt.Dimension(307, 645));

        roasted_banana.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        roasted_banana.setForeground(new java.awt.Color(135, 99, 63));
        roasted_banana.setIcon(new javax.swing.ImageIcon("F:\\Sofia\\BANANA.png")); // NOI18N
        roasted_banana.setMaximumSize(new java.awt.Dimension(307, 645));

        bourbon_vanillabean.setIcon(new javax.swing.ImageIcon("F:\\Sofia\\VAINILLA.png")); // NOI18N
        bourbon_vanillabean.setMaximumSize(new java.awt.Dimension(307, 645));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(135, 99, 63));
        jLabel2.setText("BUTTERSCOTCH BUDINO");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(135, 99, 63));
        jLabel3.setText("AMARENA CHERRY");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(135, 99, 63));
        jLabel4.setText("PASSION FRUIT");

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(135, 99, 63));
        jLabel6.setText("RUM RAISIN");

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(135, 99, 63));
        jLabel7.setText("MIXED BERRY");

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(135, 99, 63));
        jLabel8.setText("ITALIAN CUSTARD");

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(135, 99, 63));
        jLabel9.setText("ROASTED BANANA");

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(135, 99, 63));
        jLabel10.setText("BOURBON VANILLA");

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(135, 99, 63));
        jLabel11.setText("CHOCOLATE FONDENTE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(31, 31, 31)
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(butterscotch_budino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(rum_raisin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(chocolate_fondente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(68, 68, 68)
                                                                .addComponent(jLabel6))
                                                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(mixed_berry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(italian_custard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(amarena_cherry)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(passion_fruit))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(roasted_banana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addGap(30, 30, 30)
                                                                                .addComponent(jLabel7))
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addGap(6, 6, 6)
                                                                                .addComponent(jLabel9)))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(bourbon_vanillabean, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addGap(16, 16, 16)
                                                                                .addComponent(jLabel8))
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addGap(6, 6, 6)
                                                                                .addComponent(jLabel10))))))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(31, 31, 31)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel3)
                                                .addGap(31, 31, 31)
                                                .addComponent(jLabel4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtsub, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(112, 112, 112))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(17, 17, 17))))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(passion_fruit)
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(butterscotch_budino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(amarena_cherry)))
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel3)
                                                                        .addComponent(jLabel4))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(mixed_berry, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(italian_custard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(rum_raisin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(6, 6, 6)
                                                                .addComponent(jLabel2)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel7)
                                                                .addComponent(jLabel8))
                                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(roasted_banana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(chocolate_fondente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(bourbon_vanillabean, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel5)
                                                        .addComponent(txtsub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel10))
                                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Serif", 2, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ICE CREAM SHOP");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(389, 389, 389))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(30, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new shop().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel amarena_cherry;
    private javax.swing.JLabel bourbon_vanillabean;
    private javax.swing.JLabel butterscotch_budino;
    private javax.swing.JLabel chocolate_fondente;
    private javax.swing.JLabel italian_custard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel mixed_berry;
    private javax.swing.JLabel passion_fruit;
    private javax.swing.JLabel roasted_banana;
    private javax.swing.JLabel rum_raisin;
    private javax.swing.JTextField txtsub;
    // End of variables declaration

    @Override
    public void mouseClicked(MouseEvent e) {

        if(e.getSource() == rum_raisin){

            String nombre = "Rum Raisin";
            int precio = 120;

            int cantidad = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la Cantidad"));
            int total = precio * cantidad;
            modelo = (DefaultTableModel)jTable1.getModel();

            modelo.addRow(new Object[]
                    {
                            nombre,
                            precio,
                            cantidad,
                            total,
                    });
            int suma = 0;

            for(int i=0; i < jTable1.getRowCount(); i++){
                suma = suma + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
            }
            txtsub.setText(Integer.toString(suma));

        }
        else if (e.getSource() == bourbon_vanillabean){

            String nombre = "Bourbon Vanilla";
            int precio = 120;

            int cantidad = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la Cantidad"));
            int total = precio * cantidad;
            modelo = (DefaultTableModel)jTable1.getModel();

            modelo.addRow(new Object[]
                    {
                            nombre,
                            precio,
                            cantidad,
                            total,
                    });
            int suma = 0;

            for(int i=0; i < jTable1.getRowCount(); i++){
                suma = suma + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
            }
            txtsub.setText(Integer.toString(suma));

        }
        else if (e.getSource() == butterscotch_budino){

            String nombre = "Butterscotch Budino";
            int precio = 150;

            int cantidad = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la Cantidad"));
            int total = precio * cantidad;
            modelo = (DefaultTableModel)jTable1.getModel();

            modelo.addRow(new Object[]
                    {
                            nombre,
                            precio,
                            cantidad,
                            total,
                    });

            int suma = 0;

            for(int i=0; i < jTable1.getRowCount(); i++){
                suma = suma + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
            }
            txtsub.setText(Integer.toString(suma));

        }
        else if (e.getSource() == passion_fruit){

            String nombre = "Passion Fruit";
            int precio = 150;

            int cantidad = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la Cantidad"));
            int total = precio * cantidad;
            modelo = (DefaultTableModel)jTable1.getModel();

            modelo.addRow(new Object[]
                    {
                            nombre,
                            precio,
                            cantidad,
                            total,
                    });

            int suma = 0;

            for(int i=0; i < jTable1.getRowCount(); i++){
                suma = suma + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
            }
            txtsub.setText(Integer.toString(suma));

        }
        else if (e.getSource() == mixed_berry){

            String nombre = "Mixed Berry";
            int precio = 130;

            int cantidad = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la Cantidad"));
            int total = precio * cantidad;
            modelo = (DefaultTableModel)jTable1.getModel();

            modelo.addRow(new Object[]
                    {
                            nombre,
                            precio,
                            cantidad,
                            total,
                    });

            int suma = 0;

            for(int i=0; i < jTable1.getRowCount(); i++){
                suma = suma + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
            }
            txtsub.setText(Integer.toString(suma));

        }
        else if (e.getSource() == italian_custard){

            String nombre = "Italian Custard";
            int precio = 160;

            int cantidad = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la Cantidad"));
            int total = precio * cantidad;
            modelo = (DefaultTableModel)jTable1.getModel();

            modelo.addRow(new Object[]
                    {
                            nombre,
                            precio,
                            cantidad,
                            total,
                    });

            int suma = 0;

            for(int i=0; i < jTable1.getRowCount(); i++){
                suma = suma + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
            }
            txtsub.setText(Integer.toString(suma));

        }
        else if (e.getSource() == chocolate_fondente){

            String nombre = "Chocolate Fondente";
            int precio = 120;

            int cantidad = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la Cantidad"));
            int total = precio * cantidad;
            modelo = (DefaultTableModel)jTable1.getModel();

            modelo.addRow(new Object[]
                    {
                            nombre,
                            precio,
                            cantidad,
                            total,
                    });

            int suma = 0;

            for(int i=0; i < jTable1.getRowCount(); i++){
                suma = suma + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
            }
            txtsub.setText(Integer.toString(suma));

        }
        else if (e.getSource() == roasted_banana){

            String nombre = "Roasted Banana";
            int precio = 140;

            int cantidad = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la Cantidad"));
            int total = precio * cantidad;
            modelo = (DefaultTableModel)jTable1.getModel();

            modelo.addRow(new Object[]
                    {
                            nombre,
                            precio,
                            cantidad,
                            total,
                    });

            int suma = 0;

            for(int i=0; i < jTable1.getRowCount(); i++){
                suma = suma + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
            }
            txtsub.setText(Integer.toString(suma));

        }
        else if (e.getSource() == bourbon_vanillabean){

            String nombre = "Bourbon Vanilla";
            int precio = 120;

            int cantidad = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la Cantidad"));
            int total = precio * cantidad;
            modelo = (DefaultTableModel)jTable1.getModel();

            modelo.addRow(new Object[]
                    {
                            nombre,
                            precio,
                            cantidad,
                            total,
                    });

            int suma = 0;

            for(int i=0; i < jTable1.getRowCount(); i++){
                suma = suma + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
            }
            txtsub.setText(Integer.toString(suma));

        }
        else if (e.getSource() == amarena_cherry){

            String nombre = "Amarena Cherry";
            int precio = 120;

            int cantidad = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la Cantidad"));
            int total = precio * cantidad;
            modelo = (DefaultTableModel)jTable1.getModel();

            modelo.addRow(new Object[]
                    {
                            nombre,
                            precio,
                            cantidad,
                            total,
                    });

            int suma = 0;

            for(int i=0; i < jTable1.getRowCount(); i++){
                suma = suma + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
            }
            txtsub.setText(Integer.toString(suma));

        }
    }

    @Override
    public void mousePressed(MouseEvent e) {
    }

    @Override
    public void mouseReleased(MouseEvent e) {
    }

    @Override
    public void mouseEntered(MouseEvent e) {
    }

    @Override
    public void mouseExited(MouseEvent e) {
    }
}
